spring:
  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC%2B8&useSSL=true
    username: root
    password: root
    #初始化配置
    initial-size: 3
    #最小连接数
    min-idle: 3
server:
  port: 8080
  servlet:
    context-path: /
